### ISSUE TITLE
resolver error when running this in sceptre v2.3.0 and python@3.8

### ISSUE THREAD

**Issue by rohits2290** [Sceptre/sceptre-ssm-resolver#4]
I might be missing something, any help would be appreciated.
Any one else come across this issue?
I have installed sceptre-ssm-resolver
Sceptre = 2.3.0
Python@3.8

Note: I have changed the sceptre project name with <filepath>, the path is correct when I am running the sceptre launch command.

Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 11, in <module>
    load_entry_point('**sceptre==2.3.0'**, 'console_scripts', 'sceptre')()
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/**python3.8**/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/cli/launch.py", line 35, in launch_command
    plan = SceptrePlan(context)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/plan/plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/config/reader.py", line 228, in construct_stacks
    stack = self._construct_stack(rel_path, stack_group_config)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/config/reader.py", line 482, in _construct_stack
    config = self.read(rel_path, stack_group_config)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/config/reader.py", line 304, in read
    this_config = self._recursive_read(directory_path, filename, config)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/config/reader.py", line 345, in _recursive_read
    child_config = self._render(directory_path, filename, stack_group_config) or {}
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/sceptre/config/reader.py", line 392, in _render
    config = yaml.safe_load(rendered_template)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 405, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/local/Cellar/sceptre/2.3.0/libexec/lib/python3.8/site-packages/yaml/constructor.py", line 419, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!ssm'
  in "<unicode string>", line 12, column 5:
        !ssm /production/<filepath>/ ... 
        ^

**Comment by zaro0508** [comment]
I don't think sceptre supports python 3.8.  Could you please try with python 3.6?  This combination works for me:
```
➜  python -V
Python 3.6.3
➜ pip freeze|grep -i sceptre
sceptre==2.3.0
sceptre-date-resolver==1.0.0
sceptre-ssm-resolver==1.1.0
```

**Comment by rohits2290** [comment]
@zaro0508 

-> python -V
Python 2.7.16
-> python3 -V
Python 3.7.3
-> pip3 freeze|grep -i sceptre
sceptre==2.2.1
sceptre-s3-packager==0.3.0
sceptre-ssm-resolver==1.0.0

When sceptre install 2.30, brew install sceptre.

It also installs python@3.8 as dependency. If I go on to remove python@3.8 by ignoring dependency. sceptre 2.3.0 stops working.

**Comment by rohits2290** [comment]
It's working now. Thanks @zaro0508
